os: osx
language: node_js

node_js:
  - "8.1.2"

osx_image: xcode9

addons:
  apt:
    packages:
      - xvfb

cache:
  directories:
    - node_modules

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm run build
