'use strict';

const FRAME_WIDTH = 10;
const TAB_HEIGHT  = 37;

module.exports = {
	DEFAULT_WINDOW_HEIGHT: 600,
	DEFAULT_WINDOW_WIDTH: 800,
	FRAME_WIDTH: FRAME_WIDTH,
	TAB_HEIGHT: TAB_HEIGHT,
	HEIGHT_COMPENSATION: FRAME_WIDTH + TAB_HEIGHT,
	WIDTH_COMPENSATION: FRAME_WIDTH + FRAME_WIDTH
};
